services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root

  llm_service:
    build: .
    depends_on:
      - rabbitmq
    environment:
      RABBIT_USER: root
      RABBIT_PASS: root
      RABBIT_HOST: rabbitmq   # важно, совпадает с service name
